#!/bin/bash

for i in \
    azimuthalEqualArea \
    azimuthalEquidistant \
    conicConformal \
    conicEqualArea \
    conicEquidistant \
    equirectangular \
    gnomonic \
    mercator \
    orthographic \
    stereographic \
    transverseMercator; do
  test/render-world $i \
      && [ "$(compare -metric rmse test/images/$i.png test/output/$i.png null: 2>&1)" = "0 (0)" ] \
      || echo "✗ test/output/$i.png and test/images/$i.png differ"
done

for i in \
    albers \
    albersUsa; do
  test/render-us $i \
      && [ "$(compare -metric rmse test/images/$i.png test/output/$i.png null: 2>&1)" = "0 (0)" ] \
      || echo "✗ test/output/$i.png and test/images/$i.png differ"
done
