#!/usr/bin/env node

var width = 960,
    height = 500;

var fs = require("fs"),
    topojson = require("topojson"),
    Canvas = require("canvas"),
    d3 = require("d3");

var canvas = new Canvas(width, height),
    context = canvas.getContext("2d");

var world = require("./data/world-50m.json");

var graticule = d3.geo.graticule();

var path = d3.geo.path()
    .projection(d3.geo.orthographic()
        .scale(240)
        .clipAngle(90 + 1e-6))
    .context(context);

context.fillStyle = "#fff";
context.fillRect(0, 0, width, height);

context.beginPath();
path(topojson.feature(world, world.objects.land));
context.fillStyle = "#000";
context.fill();

context.beginPath();
path(graticule());
context.strokeStyle = "rgba(119,119,119,0.5)";
context.stroke();

console.warn("↳ test/images/orthographic.png");
canvas.pngStream().pipe(fs.createWriteStream("test/images/orthographic.png"));
