#!/usr/bin/env node

var width = 960,
    height = 500,
    projectionName = process.argv[2],
    projectionSymbol = "geo" + projectionName[0].toUpperCase() + projectionName.slice(1);

if (!/^[a-z0-9]+$/i.test(projectionName)) throw new Error;

var fs = require("fs"),
    topojson = require("topojson-client"),
    Canvas = require("canvas"),
    d3_geo = require("../");

var canvas = new Canvas(width, height),
    context = canvas.getContext("2d");

var world = require("world-atlas/world/50m.json"),
    graticule = d3_geo.geoGraticule(),
    outline = {type: "Sphere"};

// switch (projectionName) {
//   case "littrow": outline = graticule.extent([[-90, -60], [90, 60]]).outline(); break;
// }

var projection;

if (projectionSymbol == 'geoAngleorient30')
  projection = d3_geo.geoEquirectangular().clipAngle(90).angle(-30).precision(0.1).fitExtent([[0,0],[width,height]], {type:"Sphere"});
else
  projection = d3_geo[projectionSymbol]().precision(0.1);

var path = d3_geo.geoPath()
    .projection(projection)
    .context(context);

context.fillStyle = "#fff";
context.fillRect(0, 0, width, height);
context.save();

// switch (projectionName) {
//   case "armadillo": {
//     context.beginPath();
//     path(outline);
//     context.clip();
//     break;
//   }
// }

context.beginPath();
path(topojson.feature(world, world.objects.land));
context.fillStyle = "#000";
context.fill();

context.beginPath();
path(graticule());
context.strokeStyle = "rgba(119,119,119,0.5)";
context.stroke();

context.restore();

context.beginPath();
path(outline);
context.strokeStyle = "#000";
context.stroke();

canvas.pngStream().pipe(process.stdout);
